 
<!DOCTYPE html>
<html lang="en">
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="<?php echo $this->url->getBaseUri().'/public/css/ihatethiswork.css' ?>" rel="stylesheet">
</head>

<!--
   you can substitue the span of reauth email for a input with the email and
   include the remember me checkbox
   -->
<body>
   <div class="container">
       <div class="card card-container">
           <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
           <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
           <p id="profile-name" class="profile-name-card"></p>
           <form class="form-signin" method="post" action="">
               <span id="reauth-email" class="reauth-email"></span>
               <label>Email address</label>
               <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Enter email" required autofocus >
               <label>Password</label>
               <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required >
               <label>Firstname</label>
               <input type="text" name="firstname" class="form-control" id="firstname" placeholder="Firstname"  required  >   
                  
                <td><button type="submit" class="btn btn-info">Submit</button></td> 
                <td><a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a></td>

           </form><!-- /form -->
       </div><!-- /card-container -->
   </div><!-- /container -->
   
   <script src="<?php echo $this->url->getBaseUri().'/public/js/ihatethiswork.js' ?>"></script>
</body>
 
 
 <!-- <div class="row">
    <div class="col-sm">     
    </div>
    <div class="col-sm">
  <form action="" method="post" >
  <input type="hidden"  name="profileId"  value="<?php echo $profile->id;?>">
  <div class="form-group">
    <label>Email address</label>
    <input type="email" name="email" class="form-control" id="email" placeholder="Enter email"  required >
  </div>
  <div class="form-group">
    <label>Password</label>
    <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
  </div>
  <div class="form-group">
    <label>Firstname</label>
    <input type="text" name="firstname" class="form-control" id="firstname" placeholder="Firstname"  required  >
  </div> 
   
  <button type="submit" class="btn btn-info">Submit</button>
  
  <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>

</form>
    </div>
    <div class="col-sm">     
    </div>
  </div> -->