<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker({
        dateFormat: 'mm/dd/yy',
        yearRange: "2018:2019"
    });
  } );
  </script>
</head>

</html>
<?php echo $this->flashSession->output();?> 

<form action="" method="post" enctype="multipart/form-data">
<center>
    <label>ชื่อกิจกรรม</label>
    <input type="text" class="form-control" placeholder="ชื่อกิจกรรม" required name="name">
    <br><label>วันที่</label>
    <input type="text" class="form-control" placeholder="mm/dd/yyyy" required name="date" id="datepicker">
    <br><label>รายละเอียด</label>
    <textarea class="form-control" placeholder="รายละเอียด" required rows="4" name="details"></textarea>
    <br><label>ภาพกิจกรรม</label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
    <hr><button type="submit" class="btn btn-light">submit</button>
</center>
</form>

